let data, slide=0, timer=null, frame=0, mode=null;
const names=['Profile','Before','Conditions','Tutorial','Three-way After','Results','Future'];
const conditions=['control','rating_only','rating_history'];
const app=document.querySelector('#app'), nav=document.querySelector('#nav');
const pretty=s=>s.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const board=(f,small=false)=>`<div class="board ${small?'small':''}">${f.board.flat().map(v=>`<i class="cell ${v?'on':''}"></i>`).join('')}</div>`;
function stats(f,compact=false){let items=[['Successful placements',f.placement],['Holes',f.holes],['Stack height',f.max_height],['Bumpiness',f.bumpiness],['Lines cleared',f.lines]];return `<div class="stats ${compact?'compact':''}">${items.map(x=>`<div class="card"><span class="muted">${x[0]}</span><b>${x[1]}</b></div>`).join('')}</div>`}
function controls(){return `<div class="controls"><button onclick="play()">▶ Start</button><button onclick="pause()">Ⅱ Pause</button><button onclick="reset()">↺ Reset</button><button onclick="step()">Next step</button></div>`}
function playback(title,frames,caption){mode={kind:'single',frames};frame=Math.min(frame,frames.length-1);let f=frames[frame],note=title==='TARGETED HISTORY-AWARE TUTORIAL'?`Selected by the calibrated learner profile. ${data.tutorial.rationale}`:`${data.selection.label} · Held-out seed ${data.challenge_seed}`;return `<section class="slide"><div class="play-layout">${board(f)}<div><div class="eyebrow">${title}</div><h2>${caption}</h2>${stats(f)}<div class="piece-line">Piece <b>${f.piece||'—'}</b>${f.action?` · rotation ${f.action[0]} · x ${f.action[1]}`:''} · next <b>${f.next_piece||'—'}</b></div>${controls()}<div class="notice">${note}${f.cleared_now?' · LINE CLEAR':''}</div></div></div></section>`}
function conditionCard(condition){let frames=data.after[condition],f=frames[Math.min(frame,frames.length-1)],done=frame>=frames.length-1,c=data.conditions[condition];return `<article class="condition-panel ${done?'finished':''}"><h3>${c.title}</h3><div class="training-label">${c.training}</div>${board(f,true)}${stats(f,true)}<div class="piece-line">Piece <b>${f.piece||'—'}</b>${f.action?` · r${f.action[0]} x${f.action[1]}`:''} · next <b>${f.next_piece||'—'}</b></div><div class="panel-status">${done?`FINAL · ${frames.length-1} PLACEMENTS`:`Synchronized step ${frame}`}</div></article>`}
function comparison(){mode={kind:'comparison',frames:data.after};let max=Math.max(...conditions.map(c=>data.after[c].length));frame=Math.min(frame,max-1);return `<section class="slide comparison-slide"><div class="comparison-head"><div><div class="eyebrow">SAME HELD-OUT TEST · SEED ${data.challenge_seed}</div><h2>Three trained clones, synchronized placement by placement</h2></div><div class="integrity-badge">${data.selection.label}</div></div><div class="three-panels">${conditions.map(conditionCard).join('')}</div><div class="comparison-controls">${controls()}<span class="muted">An agent that tops out stays visible while the others continue.</span></div></section>`}
function render(){pause();mode=null;frame=0;document.querySelectorAll('.navbtn').forEach((b,i)=>b.classList.toggle('active',i===slide));document.querySelector('#position').textContent=`${slide+1} / ${names.length}`;document.querySelector('#prev').disabled=slide===0;document.querySelector('#next').disabled=slide===names.length-1;let p=data.profile;
if(slide===0)app.innerHTML=`<section class="slide"><div class="eyebrow">HOUR 7 · REPLICATE 0 · DETERMINISTIC SELECTION RULE</div><h1>History becomes a calibrated learner profile.</h1><div class="profile"><div class="card"><span class="muted">Ability / Elo</span><div class="big">${p.ability.toFixed(0)}</div></div><div class="card"><span class="muted">Hole management z</span><div class="big">${p.hole_z.toFixed(3)}</div></div><div class="card"><span class="muted">Height management z</span><div class="big">${p.height_z.toFixed(3)}</div></div><div class="card"><span class="muted">Surface management z</span><div class="big">${p.surface_z.toFixed(3)}</div></div><div class="card"><span class="muted">Primary weakness</span><div class="big">${pretty(p.primary)}</div></div><div class="card"><span class="muted">Secondary · confidence</span><div class="big">${pretty(p.secondary)}</div>${p.confidence} confidence · ${p.mixed?'mixed':'not mixed'}</div></div></div><p class="muted">${data.selection.rule}</p><div class="integrity-badge">${data.selection.label}</div></section>`;
else if(slide===1)app.innerHTML=playback('COMMON BEFORE REPLAY',data.before,'One pre-training learner, shown once');
else if(slide===2)app.innerHTML=`<section class="slide"><div class="eyebrow">THE ACTUAL THREE-CONDITION EXPERIMENT</div><h2>Same learner → cloned three ways → different training → same held-out test</h2><div class="clone-flow"><div class="clone-source">COMMON PRE-TRAINING LEARNER<br><span>identical weights, learning state, and RNG state</span></div><div class="down-arrow">↓ cloned three ways</div><div class="condition-explain">${conditions.map(c=>`<div class="card"><h3>${data.conditions[c].title}</h3><p>${data.conditions[c].training}</p></div>`).join('')}</div><div class="down-arrow">↓ identical held-out piece stream · seed ${data.challenge_seed}</div></div><div class="integrity-badge">${data.selection.label}</div></section>`;
else if(slide===3)app.innerHTML=playback('TARGETED HISTORY-AWARE TUTORIAL',data.tutorial.frames,`${pretty(p.primary)} · ${pretty(data.tutorial.type)}`);
else if(slide===4)app.innerHTML=comparison();
else if(slide===5){let r=data.results;app.innerHTML=`<section class="slide"><div class="eyebrow">SAVED AGGREGATE HOUR 6/7 RESULTS</div><h2>Inference comes from all matched replicates—not the animation</h2><div class="results"><div class="card"><h3>Rating + history vs control</h3>${rr('Hour 6',r['6'].rating_history_minus_control)}${rr('Hour 7',r['7'].rating_history_minus_control)}</div><div class="card"><h3>Rating + history vs rating-only</h3>${rr('Hour 6',r['6'].rating_history_minus_rating_only)}${rr('Hour 7',r['7'].rating_history_minus_rating_only)}</div></div><p>History-aware training showed a more consistent advantage over rating-only training than over ordinary practice. The results are promising but not yet conclusive.</p><div class="notice">The intended target-skill teaching mechanism has not yet been demonstrated.</div></section>`}
else app.innerHTML=`<section class="slide"><div class="eyebrow">FUTURE WORK</div><h2>Next question: Can the teacher learn how to teach?</h2><div class="flow"><span>Persistent learning<br>agents</span><b class="arrow">→</b><span>Profiles update</span><b class="arrow">→</b><span>Teacher chooses<br>tutorial parameters</span><b class="arrow">→</b><span>Learner trains</span><b class="arrow">→</b><span>Held-out<br>improvement</span><b class="arrow">→</b><span>Teacher updates<br>strategy</span><b class="arrow">↻</b></div><div class="future-test">FREEZE LEARNED TEACHER<br>↓<br><b>TEST ON FRESH HELD-OUT AGENTS</b></div><p>Students learn how to play while the teacher learns which training experiences produce the greatest subsequent improvement.</p><p class="muted">AlphaZero-like in iterative learning from repeated experience—not necessarily its exact architecture.</p></section>`}
function rr(label,x){return `<div class="result-row"><span>${label}</span><span class="estimate">${x.paired_mean_difference>=0?'+':''}${x.paired_mean_difference.toFixed(3)}</span><span class="ci">95% CI [${x.ci95[0].toFixed(3)}, ${x.ci95[1].toFixed(3)}]</span></div>`}
function redraw(){if(!mode)return;let keep=frame;if(mode.kind==='comparison')app.innerHTML=comparison();else {let title=slide===1?'COMMON BEFORE REPLAY':'TARGETED HISTORY-AWARE TUTORIAL';let caption=slide===1?'One pre-training learner, shown once':`${pretty(data.profile.primary)} · ${pretty(data.tutorial.type)}`;app.innerHTML=playback(title,mode.frames,caption)}frame=keep}
function lastFrame(){return mode.kind==='comparison'?Math.max(...conditions.map(c=>mode.frames[c].length))-1:mode.frames.length-1}
function play(){pause();timer=setInterval(()=>{if(frame>=lastFrame())return pause();frame++;redraw()},520)}function pause(){if(timer)clearInterval(timer);timer=null}function reset(){pause();frame=0;redraw()}function step(){pause();frame=Math.min(frame+1,lastFrame());redraw()}
names.forEach((n,i)=>{let b=document.createElement('button');b.className='navbtn';b.textContent=n;b.onclick=()=>{slide=i;render()};nav.appendChild(b)});document.querySelector('#prev').onclick=()=>{slide--;render()};document.querySelector('#next').onclick=()=>{slide++;render()};
fetch('demo_data.json').then(r=>r.json()).then(d=>{data=d;render()}).catch(e=>app.innerHTML=`<h2>Could not load demo data</h2><p>${e}</p>`);
