let data, slide=0, timer=null, frame=0, mode=null;
const names=['Intro','Before','Tutorial','After','Results','Future'];
const app=document.querySelector('#app'), nav=document.querySelector('#nav');
const pretty=s=>s.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const board=f=>`<div class="board">${f.board.flat().map(v=>`<i class="cell ${v?'on':''}"></i>`).join('')}</div>`;
function stats(f){return `<div class="stats"><div class="card"><span class="muted">Placements</span><b>${f.placement}</b></div><div class="card"><span class="muted">Holes</span><b>${f.holes}</b></div><div class="card"><span class="muted">Max height</span><b>${f.max_height}</b></div><div class="card"><span class="muted">Bumpiness</span><b>${f.bumpiness}</b></div><div class="card"><span class="muted">Lines cleared</span><b>${f.lines}</b></div><div class="card"><span class="muted">Current piece</span><b>${f.piece||'—'}</b></div></div>`}
function playback(title,frames,caption){mode=frames;frame=Math.min(frame,frames.length-1);let f=frames[frame],note=title==='TARGETED TUTORIAL'?`This is the tutorial selected by the learner model. ${data.tutorial.rationale}`:`${data.selection.label} · Held-out seed ${data.challenge_seed}`;return `<section class="slide"><div class="play-layout">${board(f)}<div><div class="eyebrow">${title}</div><h2>${caption}</h2>${stats(f)}<div class="controls"><button onclick="play()">▶ Start</button><button onclick="pause()">Ⅱ Pause</button><button onclick="reset()">↺ Reset</button><button onclick="step()">Next step</button></div><div class="notice">${note}${f.cleared_now?' · LINE CLEAR':''}</div></div></div></section>`}
function render(){pause();mode=null;frame=0;document.querySelectorAll('.navbtn').forEach((b,i)=>b.classList.toggle('active',i===slide));document.querySelector('#position').textContent=`${slide+1} / 6`;document.querySelector('#prev').disabled=slide===0;document.querySelector('#next').disabled=slide===5;let p=data.profile;if(slide===0)app.innerHTML=`<section class="slide"><div class="eyebrow">ONE LEARNER. ONE FAIR CHALLENGE.</div><h1>Player history → calibrated learner profile → tutorial selection.</h1><div class="profile"><div class="card"><span class="muted">Ability / Elo</span><div class="big">${p.ability.toFixed(0)}</div></div><div class="card"><span class="muted">Hole management z</span><div class="big">${p.hole_z.toFixed(3)}</div></div><div class="card"><span class="muted">Height management z</span><div class="big">${p.height_z.toFixed(3)}</div></div><div class="card"><span class="muted">Surface management z</span><div class="big">${p.surface_z.toFixed(3)}</div></div><div class="card"><span class="muted">Primary weakness</span><div class="big">${pretty(p.primary)}</div></div><div class="card"><span class="muted">Secondary · confidence</span><div class="big">${pretty(p.secondary)}</div>${p.confidence} confidence · ${p.mixed?'mixed':'not mixed'}</div></div></div><p class="muted">${data.selection.study}, replicate ${data.selection.replicate}. ${data.selection.label}</p></section>`;
else if(slide===1)app.innerHTML=playback('BEFORE TRAINING',data.before,'Held-out ordinary Tetris challenge');
else if(slide===2)app.innerHTML=playback('TARGETED TUTORIAL',data.tutorial.frames,`${pretty(p.primary)} · ${pretty(data.tutorial.type)}`)+'';
else if(slide===3)app.innerHTML=playback('AFTER TRAINING',data.after,'The same held-out challenge')+'';
else if(slide===4){let r=data.results;app.innerHTML=`<section class="slide"><div class="eyebrow">SAVED AGGREGATE RESULTS</div><h2>History-aware training</h2><div class="results"><div class="card"><h3>vs control</h3>${rr('Hour 6',r['6'].rating_history_minus_control)}${rr('Hour 7',r['7'].rating_history_minus_control)}</div><div class="card"><h3>vs rating-only</h3>${rr('Hour 6',r['6'].rating_history_minus_rating_only)}${rr('Hour 7',r['7'].rating_history_minus_rating_only)}</div></div><p>History-aware training showed a more consistent advantage over rating-only training than over ordinary practice. The results are promising but not yet conclusive.</p><div class="notice">The intended target-skill teaching mechanism has not yet been demonstrated.</div></section>`}
else app.innerHTML=`<section class="slide"><div class="eyebrow">FUTURE WORK</div><h2>Next question: Can the teacher learn how to teach?</h2><div class="flow"><span>Small cohort of persistent<br>learning agents</span><b class="arrow">→</b><span>Thousands of games;<br>profiles update</span><b class="arrow">→</b><span>Teacher chooses<br>tutorial parameters</span><b class="arrow">→</b><span>Learner trains</span><b class="arrow">→</b><span>Measure held-out<br>improvement</span><b class="arrow">→</b><span>Teacher updates<br>strategy</span><b class="arrow">↻</b></div><div class="future-test">FREEZE LEARNED TEACHER<br>↓<br><b>TEST ON FRESH HELD-OUT AGENTS</b></div><p>Students learn how to play while the teacher learns which training experiences produce the greatest subsequent improvement.</p><p class="muted">AlphaZero-like in iterative learning from repeated experience—not necessarily its exact MCTS/neural-network architecture.</p></section>`
}
function rr(label,x){return `<div class="result-row"><span>${label}</span><span class="estimate">${x.paired_mean_difference>=0?'+':''}${x.paired_mean_difference.toFixed(3)}</span><span class="ci">95% CI [${x.ci95[0].toFixed(3)}, ${x.ci95[1].toFixed(3)}]</span></div>`}
function redraw(){if(mode){let keep=frame;app.innerHTML=playback(slide===1?'BEFORE TRAINING':slide===2?'TARGETED TUTORIAL':'AFTER TRAINING',mode,slide===2?`${pretty(data.profile.primary)} · This is the tutorial selected by the learner model.`:slide===1?'Held-out ordinary Tetris challenge':'The same held-out challenge');frame=keep}}
function play(){pause();timer=setInterval(()=>{if(frame>=mode.length-1)return pause();frame++;redraw()},520)}function pause(){if(timer)clearInterval(timer);timer=null}function reset(){pause();frame=0;redraw()}function step(){pause();frame=Math.min(frame+1,mode.length-1);redraw()}
names.forEach((n,i)=>{let b=document.createElement('button');b.className='navbtn';b.textContent=n;b.onclick=()=>{slide=i;render()};nav.appendChild(b)});document.querySelector('#prev').onclick=()=>{slide--;render()};document.querySelector('#next').onclick=()=>{slide++;render()};
fetch('demo_data.json').then(r=>r.json()).then(d=>{data=d;render()}).catch(e=>app.innerHTML=`<h2>Could not load demo data</h2><p>${e}</p>`);
